#!/usr/bin/env python3
"""
Teknic ClearPath SDSK step/direction test (Raspberry Pi 5).

Uses lgpio (the native, best-compatible GPIO library for the Pi 5 RP1
chip). Step pulses are generated by the hardware DMA timer via tx_pwm,
which gives a rock-steady frequency that ClearPath needs - far more
reliable than a software time.sleep() pulse loop.

Wiring (BCM numbering):
    STEP_PIN = 23  -> ClearPath Input B (Step)
    DIR_PIN  = 24  -> ClearPath Input A (Direction)
    EN_PIN   = 25  -> ClearPath Enable
"""

import time
import lgpio

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
STEP_PIN = 23
DIR_PIN = 24
EN_PIN = 25

STEP_FREQ = 2000    # step pulses per second (Hz)
STEP_DUTY = 50      # % duty cycle of the step pulse (50% = symmetric)
MOVE_SECONDS = 5    # duration for the timed forward/reverse moves

FORWARD = 1
REVERSE = 0

# ClearPath needs a moment after Enable is asserted before it will move.
ENABLE_SETTLE_S = 0.5


# ---------------------------------------------------------------------------
# GPIO setup
# ---------------------------------------------------------------------------
def open_chip():
    """Open the header gpiochip.

    On current Raspberry Pi OS the 40-pin header is exposed as
    gpiochip0 (pinctrl-rp1) on the Pi 5 and on earlier boards alike
    (confirm with `gpiodetect`). 4 is kept as a fallback for older
    Pi 5 kernels that numbered the RP1 header chip as gpiochip4.
    """
    for chip in (0, 4):
        try:
            return lgpio.gpiochip_open(chip)
        except lgpio.error:
            continue
    raise RuntimeError("No usable gpiochip found")


h = open_chip()
lgpio.gpio_claim_output(h, STEP_PIN, 0)
lgpio.gpio_claim_output(h, DIR_PIN, FORWARD)
lgpio.gpio_claim_output(h, EN_PIN, 0)

enabled = False
running = False
current_direction = FORWARD


# ---------------------------------------------------------------------------
# Motion helpers
# ---------------------------------------------------------------------------
def set_enable(state):
    global enabled
    lgpio.gpio_write(h, EN_PIN, 1 if state else 0)
    enabled = bool(state)
    if state:
        time.sleep(ENABLE_SETTLE_S)
    print("Motor ENABLED" if state else "Motor DISABLED")


def set_direction(direction):
    global current_direction
    current_direction = direction
    lgpio.gpio_write(h, DIR_PIN, direction)


def start_motion(direction):
    """Begin a continuous, hardware-timed pulse train."""
    global running
    if not enabled:
        set_enable(True)
    stop_motion()
    set_direction(direction)
    # pulse_cycles = 0 -> run continuously until stopped.
    lgpio.tx_pwm(h, STEP_PIN, STEP_FREQ, STEP_DUTY, pulse_cycles=0)
    running = True
    print("Running", "FORWARD" if direction == FORWARD else "REVERSE",
          f"@ {STEP_FREQ} Hz")


def stop_motion():
    global running
    lgpio.tx_pwm(h, STEP_PIN, STEP_FREQ, 0)   # duty 0 -> pulses stop
    lgpio.gpio_write(h, STEP_PIN, 0)
    running = False


def move_for_seconds(direction, seconds):
    start_motion(direction)
    time.sleep(seconds)
    stop_motion()
    print("Move complete")


def toggle_direction():
    new_dir = REVERSE if current_direction == FORWARD else FORWARD
    set_direction(new_dir)
    print("Direction now:", "FORWARD" if new_dir == FORWARD else "REVERSE")


def cleanup():
    stop_motion()
    lgpio.gpio_write(h, EN_PIN, 0)
    lgpio.gpiochip_close(h)


# ---------------------------------------------------------------------------
# Menu
# ---------------------------------------------------------------------------
MENU = """
=== CLEARPATH SDSK TEST ===
1. Forward {sec} sec
2. Reverse {sec} sec
3. Continuous Forward
4. Continuous Reverse
5. Enable motor
6. Disable motor
7. Stop
8. Toggle direction
9. Set step frequency (Hz)
0. Quit
""".format(sec=MOVE_SECONDS)


def main():
    global STEP_FREQ
    try:
        while True:
            print(MENU)
            print(f"[state] enabled={enabled} running={running} "
                  f"freq={STEP_FREQ}Hz "
                  f"dir={'FWD' if current_direction == FORWARD else 'REV'}")
            choice = input("> ").strip()

            if choice == "1":
                move_for_seconds(FORWARD, MOVE_SECONDS)
            elif choice == "2":
                move_for_seconds(REVERSE, MOVE_SECONDS)
            elif choice == "3":
                start_motion(FORWARD)
            elif choice == "4":
                start_motion(REVERSE)
            elif choice == "5":
                set_enable(True)
            elif choice == "6":
                stop_motion()
                set_enable(False)
            elif choice == "7":
                stop_motion()
                print("Stopped")
            elif choice == "8":
                toggle_direction()
            elif choice == "9":
                try:
                    STEP_FREQ = max(1, int(input("New frequency (Hz): ")))
                    if running:
                        start_motion(current_direction)
                    print("Frequency set to", STEP_FREQ, "Hz")
                except ValueError:
                    print("Invalid number")
            elif choice == "0":
                break
            else:
                print("Invalid choice")

    except KeyboardInterrupt:
        print("\nInterrupted")
    finally:
        cleanup()
        print("Cleanup complete")


if __name__ == "__main__":
    main()